### ISSUE TITLE
Implement additional motion descriptors (with matching prompts) as input for LLM-generated feedback 

### ISSUE THREAD

**Issue by j55blanchet** [j55blanchet/dance-teacher-xr-unity#43]
We're looking to use a LLM to generate human-like coaching feedback for our dance learners.

To do that, we'll do the following:

1. Capture user's dance using pose estimation (already implemented)
2. Compute motion descriptors to include in an evaluation report (partially implemented)
3. Send evaluation report to our server, which then forwards it to the LLM, alongside instructions on how to interpret the report and the type of feedback we're looking for 
4. LLM returns spoken / text (or other?) feedback, which we present to the user (perhaps using text-to-speech)..

This issue involves fleshing out / implemented the second step.

**Comment by sixuanhan** [comment]
The code is now able to compute `sdJerks` in `getPerformanceSummary` in the evaluator.

After initial testing, I've found that

1. `sdJerks` is able to remain stable through different but similar trials. When I stood still for 3 rounds, they all yielded scores around 600.
2.  `sdJerks` is able to reflect differences in jerks. Standing still: sdJerks = 600. Crazily twitching my arms = 1900.

I have not run into edge cases where I am not able to compute `sdJerks`, therefore I can't guarantee that it works for all cases. However, I have added many checks for undefined values, bad array length, etc. so I'm confident that it can handle errors well.

However, there are still concerns about `sdJerks`.

1. When I tried to do my best, `sdJerks` is still pretty high, sometimes even higher than when I stood still.
2. It is hard to define a threshold to tell how good/matching the user's jerk is. There is no way to normalize it like we did for skeleton dissimilarity.
3. How did we take the slowing of the speed into consideration? How do we match the frametime of a slowed-down user's record to the reference poses in normal speed?

**Comment by sixuanhan** [comment]
I've been discussing about the standard deviation of jerks between the user's and the reference's. 

The raw jerks is a 3D array `jerks[timestamp][joint_Index][x_or_y]`. So if I compare two `poselandmarks[]` that are exactly the same, `sdJerks` should be 0, because it calculates the standard deviation. 0 is the best score that a user can get and there is no upper limit for the worst score. I personally believe that **the goal is not to be not jerky; the goal is to be as jerky as the reference is**.

For the user, ideally, the goal is to lower the `sdJerks` score to as low as they can get, but this does not imply whether they are not jerky enough or they are too jerky. I guess this relates to raw scores vs. comparative scores. However, simply calculating the sum of jerks or a mean of jerks might not be really informative because I stored jerks as vectors instead of scalars and summing them will take away directional meanings. I can probably write a function to calculate the means of jerks as scalars.

Let's talk about the third point tomorrow.

**Comment by j55blanchet** [comment]
Will separate this issue into metric-specific issues
