### ISSUE TITLE
Validate / test out current feedback computation

### ISSUE THREAD

**Issue by j55blanchet** [j55blanchet/dance-teacher-xr-unity#44]

**Comment by sixuanhan** [comment]
We discovered from our limited experience with the system that we generally get a pretty high score no matter how well we do. So we decided to test
1. different dances
2. different levels of completion
to see whether the current computation of the feedback is desirable.

**Comment by sixuanhan** [comment]
Here is the result after a simple round of testing:
<img width="571" alt="Screenshot 2023-09-13 at 11 16 05 PM" src="https://github.com/j55blanchet/dance-teacher-xr-unity/assets/120262254/9ea70cb2-6e30-497f-984d-07de61cfd97c">

Given that

1. The difference between not doing anything at all (standing still and facing sideways), minimal effort, and great effort is not significant at all.
2. The score for not doing anything at all and minimal effort are too high.
3. By observing the skeleton color coding, I realized that the algorithm could not identify the orientation of my body (eg. the skeleton thought I was facing the front even when I was facing sideways and facing the back.

I believe that our current calculation is indeed flawed. 

Some intuitive fixes:

1. give weights to different joints and lower the weight of the body box (shoulders + hip joints)
2. improve the algorithm somehow so that it knows my body orientation
3. be stricter. The user loses more point for being incorrect

**Comment by j55blanchet** [comment]
Nice job testing this! Very helpful to document the ways in which the current approach (`computeSkeletonDissimilarityQijiaMethod`) falls short.

This does motivate the creation of an updated skeleton similarity metric, and we can use your intuitive fixes as a starting point.

Taking a step back, it seems important to me that we have a consistent way to test and compare different evaluation methods / metrics. This is also an opportunity to add testing to the app. I'm thinking the following:
1. Create a library of user performances. We can record, run pose estimation, and save the user performances as csv files. We should have multiple levels of effort and for different dances. We can add to this as time goes on, as a way to test other evaluation metrics we can compute in addition to skeleton similarity.
2. Setup a unit testing framework for our svelte app, like vitest: <https://testing-library.com/docs/svelte-testing-library/setup>.
3. Add tests for different evaluation methods, which will read the csv file and then call the different evaluation methods on them.
